### ISSUE TITLE
changed wordlist gives newline

### ISSUE THREAD

**Issue by PeterAlfonsLoch** [sindresorhus/random-word#4]
I changed the wordlist, now it always gives the words with a new line at the end, i cant find a way to get rid of that, i do not know why it does that either....

**Comment by PeterAlfonsLoch** [comment]
with the old wordlist it doesnt do that....

**Comment by sindresorhus** [comment]
It only splits on `\n`, not `\r\n`, since the source file is only using `\n`. This is something you'll need to fix yourself though. It has nothing to do with the package itself, which is working fine when not modified.
