### ISSUE TITLE
faker alternative

### ISSUE THREAD

**Issue by mfulton26** [sindresorhus/random-word#6]
with the recent things in the news about `colors` and `faker` projects I image many folks will increasingly be looking for alternatives to those libraries (perhaps not, perhaps I am missing more context here and need to be politically educated)

either way; I think updating this package with TypeScript types, etc., etc. and publishing a new version might be really helpful for those looking for alternative implementations for things they've relied on faker for in the past

**Comment by mfulton26** [comment]
or perhaps you have some alternative packages you can recommend; thanks!

**Comment by sindresorhus** [comment]
https://github.com/ngneat/falso

**Comment by mfulton26** [comment]
thank you; that looks like a new, promising library
